django/blog/blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blogapp import views
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include("blogapp.urls")),
    url(r'^favicon\.ico/$',RedirectView.as_view(url='/static/favicon.ico'),name = 'favicon'),
]

django/blog/blogapp/urls.py
#coding=utf-8

from django.conf.urls import url
from blogapp.views import *


urlpatterns = [
    url(r'^page/$',mainpage,{"datas":""}),
    url(r'^page/all/$', mainpage,{"datas":1}),
    url(r'^page/sces/$', mainpage,{"datas":2}),
    url(r'^page/travel/$', mainpage,{"datas":3}),
    url(r'^myself/$',myself),
    url(r'^write/$', write),
    url(r'^look/$', look),
    url(r'^$',login),
    url(r'^reg/$', reg),
    url(r'^logout/$',logout),
]

django/blog/blogapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    avater = models.ImageField(max_length = 200,blank = True,null = True,verbose_name = "Head_portrait")
    mobile = models.CharField(max_length = 11,blank = True,null = True,verbose_name = "tel")
    class Meta:
        verbose_name = "User"
        ordering = ['-id']
    def __unicode__(self):
        return self.username

# class user(models.Model):
#     username = models.CharField(max_length = 30)
#     sex = models.CharField(max_length = 30)
#     age = models.IntegerField()
#     email = models.EmailField(blank = True,verbose_name = 'e-mail')

class title(models.Model):
    title = models.CharField(max_length = 100)
    content = models.CharField(max_length = 2000)
    time = models.CharField(max_length = 50)
    tag = models.CharField(max_length = 5)
    def __unicode__(self):
        return self.title

django/blog/blogapp/forms.py
#coding=utf-8
from django import forms
from blogapp.models import User,title

TOPIC_CHOICES = (
    ('a','新闻'),
    ('t','旅游'),
    ('s','技术'),
)

class RemarkForm(forms.Form):
    title = forms.CharField(max_length = 100,label = '标题')
    content = forms.CharField(label = '内容',widget = forms.Textarea)
    time = forms.CharField(max_length = 50,label = '时间')
    tag = forms.ChoiceField(choices = TOPIC_CHOICES,label = '类别')

django/blog/blogapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
import time
from models import *
from forms import *
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required,permission_required
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
from django.contrib.sessions.models import Session
# Create your views here.

name = "wait"
def page(request,datas):
    paginator = Paginator(datas,3)

    #获取当前页为几页
    p = int(request.GET.get('page',1))

    datas = paginator.page(p)

    return datas


def mainpage(request,datas):
    if datas:
        data = int(datas)
        if data == 1:
            page = 1
            databases = title.objects.all()

            paginator = Paginator(databases,3)
            #获取当前页为几页
            p = int(request.GET.get('pags',1))
            articles = paginator.page(p)

            pages = range(1,articles.paginator.num_pages + 1)

            return render(request,"mainpage.html",locals())
        elif data == 2:
            page = 2
            databases = title.objects.filter(tag = "s")
            paginator = Paginator(databases,3)
            #获取当前页为几页
            p = int(request.GET.get('pags',1))
            articles = paginator.page(p)

            pages = range(1,articles.paginator.num_pages + 1)
            return render(request,"mainpage.html",locals())
        elif data == 3:
            page = 3
            databases = title.objects.filter(tag = "t")
            paginator = Paginator(databases,3)
            #获取当前页为几页
            p = int(request.GET.get('pags',1))
            articles = paginator.page(p)

            pages = range(1,articles.paginator.num_pages + 1)
            return render(request,"mainpage.html",locals())
    else:
        page = 11
        return render(request,"mainpage.html",locals())



def myself(request):
    page = 10
    if name == 'wait':
        return HttpResponseRedirect('/')
    names = request.session['username']
    print name
    users = User.objects.filter(username = name)
    return render(request,"mainpage.html",locals())

def write(request):
    page = 12
    if request.method == 'POST':
        times = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        title.objects.create(title = request.POST.get('title'),content = request.POST.get('content'),time = times,tag = request.POST.get('lei'))
    return render(request,'mainpage.html',locals())

def look(request):
    page = 13
    datas = request.GET.get("ids","")
    if datas:
        databases = title.objects.get(id = datas)
    return render(request,'mainpage.html',locals())
def reg(request):
    a = 0
    try:
        if request.method == 'POST':
            username = request.POST.get("username",'')
            password = request.POST.get("password",'')
            email = request.POST.get("email",'')
            if username:
                dic = {
                'username':username,
                'password':make_password(password),
                'email':email
                }
                User.objects.create(**dic)

                return HttpResponseRedirect("/")
            else:
                return render(request,'login.html',{'reason':reg_form.errors})
        else:
            return render(request,'login.html',locals)
    except Exception as e:
        print e
    return render(request,'login.html',locals())

def login(request):
    a = 1
    if request.method == "POST":
        username = request.POST.get('username',"")
        password = request.POST.get('password',"")

        #这是判断用户没有登录
        if not request.user.is_authenticated():
            user = auth.authenticate(username = username,password = password)
            if user is not None and user.is_active:
                #这里是让user登录
                auth.login(request,user)
                request.session['username'] = username
                global name
                name = request.session['username']
                # return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))
                # return HttpResponseRedirect(request.GET.get('next','/'))
                return HttpResponseRedirect('/page/')
            else:
                return HttpResponse("username or password invalid")
        else:
        #这里是已经存在登录的账号，存在就直接进入主页面
            global name
            name = request.session['username']
            return HttpResponseRedirect("/page/")
    return render(request,"login.html",locals())

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

django/blog/blogapp/templates/article.html
<div class="container artic_can">
  <div class="article write">
    <form enctype="multipart/form-data" action="" method="post" id="article_form" class="write_form">
      {%csrf_token%}
      <fieldset class="module aligned ">
        <div class="form-row field-title">
            <span>标题：</span>
            <input type="text" required name="title" id="id_title"  maxlength="50" class="form-control"/>
        </div>
        <br>
        <div class="form-row field-desc">
            <span>类别：</span>
            <select size="1" name="lei" class="btn btn-success">
              <option value="a" selected="selected">杂文</option>
              <option value="t">旅游</option>
              <option value="s">技术</option>
            </select>
        </div>
        <div class="form-row field-content">
            <span>内容：</span>
            <textarea name="content" id="id_content" class='form-control cons'></textarea>
        </div>
        <button class="btn btn-success" type="submit">提交</button>
      </form>
    </div>
  </div>

django/blog/blogapp/templates/head.html
<div class="nav container">Clark blog
  <div class="text">不要温顺地走进那个良夜，激情不能被消沉的暮色退缩，咆哮吧咆哮，痛斥那光的退缩！</div>
  <div class="xiala">
    <div class="hidde"></div>
    <div class="xiala1">
      <div class="xiala_ul">
        <a href="/page"><span><b>首页</b></span></a>
        <a href="/page/all"><span><b>杂文趣事</b></span></a>
        <a href="/page/sces"><span><b>技术达人</b></span></a>
        <a href="/page/travel"><span><b>旅游生活</b></span></a>
        <a href="/myself"><span><b>Myself</b></span></a>
      </div>
    </div>
  </div>
</div>

django/blog/blogapp/templates/login.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>
  <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">
  <title>登录</title>
  <style>
  * {
    margin:0px;
    padding:0px;
  }
  body {
    background: #060e1b;
  }
  .form {
    width:400px;
    height:350px;
    border:1px solid #fff;
    box-shadow: 0 0 10px #fff;
    padding:0px;
    border-radius: 5px;
    display: inline-block;
    background: rgba(6,14,27, 0.5);
    position: absolute;
    left:50%;
    top:50%;
    margin-left: -200px;
    margin-top: -200px;

  }
  .tits {
    height:40px;
    font-size: 25px;
    color:blue;
    text-align: center;
    line-height: 40px;
    margin-bottom: 5px;
    background: rgba(220,220,220,0.5);
    border-radius: 5px;
  }
  .form-group {
    padding:0px 10px;
    color:blue;
    font-size: 20px;
  }
  .clark {
    color:yellow;
    text-align: center;
    font-size: 30px;
  }
  </style>
</head>
<body>
<canvas id="canvas"></canvas>
  {%if a == 1%}
  <form method="post" class="container form">
    {%csrf_token%}
    <div class="tits">登录</div>
    <div class="form-group">
      <label for="exampleInputEmail1">用户名:</label>
      <input type="text" class="form-control" id="exampleInputEmail1" placeholder="请输入用户号" required name="username">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">密　码:</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="请输入密码" required name="password">
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-success">登 录</button>
      <a href="/reg/" class="btn btn-success">注 册</a>
    </div>

    <div class="clark">clark blog</div>

  </form>
  {%elif a == 0%}
  <form method="post" class="container form">
    {%csrf_token%}
    <div class="tits">注册</div>
    <div class="form-group">
      <label for="exampleInputEmail1">用户名:</label>
      <input type="text" class="form-control" id="exampleInputEmail1" placeholder="请输入用户号" required name="username">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">密　码:</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="请输入密码" required name="password">
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">密　码:</label>
      <input type="email" class="form-control" id="exampleInputPassword1" placeholder="请输入邮箱" required name="email">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-success">注 册</button>
      <a href="/" class="btn btn-success">返回登录</a>
    </div>
  </form>
  {%endif%}
  <script src="{%static 'js/canvas.js'%}" charset="utf-8"></script>
  <script type="text/javascript">

  </script>
</body>
</html>

django/blog/blogapp/templates/lunbo.html
{%load static%}
<div class="container lun">
  <div class="box" id="box-id">
      <ul class="image" id="img-id">
        <li class="current"><a href="#"><img src="{%static 'images/mi/4.jpg'%}" alt=""></a></li>
          <li><a href="#"><img src="{%static 'images/mi/2.jpg'%}" alt=""></a></li>
          <li><a href="#"><img src="{%static 'images/mi/3.jpg'%}" alt=""></a></li>
          <li><a href="#"><img src="{%static 'images/mi/1.jpg'%}" alt=""></a></li>
      </ul>
      <div class="point" id="point-id"></div>
  </div>
</div>

django/blog/blogapp/templates/mainpage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>
  <script type="text/javascript" src="/static/js/kindeditor-4.1.10/kindeditor-min.js"></script>
  <script type="text/javascript" src="/static/js/kindeditor-4.1.10/lang/zh_CN.js"></script>
  <script type="text/javascript" src="/static/js/kindeditor-4.1.10/config.js"></script>
</head>
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>
  <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">
  <link rel="stylesheet" href="{%static 'css/lunbo.css'%}">
  <link rel="icon" type="image/ico" href="{%static 'images/favicon.ico'%}" />
  <title>个人博客</title>
  <style>
  * {
    margin:0px;
    padding:0px;
  }
  body {
    /*background: url("{% static 'images/11.jpg' %}");*/
    /*background-size:cover;*/
    background: #000;
  }
  canvas {
  	display: block;
  }
  .nav {
    height:100px;
    line-height: 100px;
    color:yellow;
    text-shadow: 0 0 20px green;
    font-size: 40px;
    padding-left: 50px;
    box-shadow: 0 0 5px yellow;
    position: absolute;
    top:0px;
    left:50%;
    margin-left: -585px;
    border-radius: 5px;
    background: rgba(72, 118, 255, 0.2);
  }
  .text {
    padding-left: 30px;
    font-size: 15px;
    display: inline-block;
    background-image: linear-gradient(to right,#ff5200,#bf3eff,#7fff00);
    text-shadow: 0 0 10px yellow;
    -webkit-background-clip:text;
    -webkit-text-fill-color: transparent;
  }
  .xiala {
    width:60px;
    height:60px;
    border-radius: 30px;
    position:absolute;
    right:30px;
    top:20px;
    color:#0000ff;
    background: url("{%static 'images/su.jpg'%}") no-repeat center;
    background-size: 100px 100px;
    display: inline-block;
  }
  .xiala:hover .hidde{
    display: block;
  }
  .hidde {
    width:300px;
    height:150px;
    position:absolute;
    right:-50px;
    display: none;
  }
  .xiala1 {
    width:1100px;
    height:200px;
    position:absolute;
    right:-15px;
    bottom:-260px;
    z-index: -3;
    display: none;
  }
  .xiala1_ul {
    position: absolute;
    z-index: -4;
  }
  .xiala_ul a {
    border-radius: 5px;
    width:199px;
    margin-left: 17px;
    margin-top:1px;
    height:177px;
    float:left;
    font-size: 15px;
    text-decoration: none;
  }
  .xiala_ul a:nth-child(1){
    background: url("{%static 'images/0.jpg'%}") -35px 0px;
    background-size: cover;
    box-shadow: 0px 0px 50px yellow;
    color:#fff;
  }
  .xiala_ul a:nth-child(2){
    background: url("{%static 'images/4.jpg'%}");
    background-size: cover;
    box-shadow: 0px 0px 50px #0000ff;
    color:#00ff00;
  }
  .xiala_ul a:nth-child(3){
    background: url("{%static 'images/3.jpg'%}") 0px -2px;
    background-size: 200px 190px;
    box-shadow: 0px 0px 50px green;
    color:#0000ff;
  }
  .xiala_ul a:nth-child(4){
    background: url("{%static 'images/2.jpg'%}");
    background-size: cover;
    box-shadow: 0px 0px 50px red;
    color:#ffff00;
  }
  .xiala_ul a:nth-child(5){
    background: url("{%static 'images/1.jpg'%}");
    background-size: contain;
    box-shadow: 0px 0px 50px orange;
    color:blue;
  }
  .xiala_ul a span {
    width:199px;
    height:177px;
    font-size: 30px;
    line-height: 177px;
    display: block;
    text-align: center;
    position:relative;
    opacity:0;
    z-index: -1;
    border-radius: 5px;
    transition: all 0.5s ease-in;
  }
  .xiala_ul a:hover span{
    z-index: 100;
    opacity: 0.5;
  }
  .xiala_ul a:nth-child(1) span{
    background: red;
  }
  .xiala_ul a:nth-child(2) span{
    background: purple;
  }
  .xiala_ul a:nth-child(3) span{
    background: orange;
  }
  .xiala_ul a:nth-child(4) span{
    background: green;
  }
  .xiala_ul a:nth-child(5) span{
    background: #9aff9a;
  }
  .center {
    position: absolute;
    left:50%;
    top:50%;
    margin-left: -585px;
    margin-top: -230px;
  }
  .article {
    width:800px;
    margin-top: 50px;
    border:1px solid lightblue;
    box-shadow: 0 0 20px #fff;
    padding:5px;
    background: rgba(255, 228, 225, 0.2);
    position: absolute;
    border-radius: 5px;
  }
  .titles {
    width:790px;
    /*height:100px;*/
    border-bottom: 1px solid #fff;
  }
  .titles .tit {
    font-size: 20px;
    color:#32cd32;
  }
  .tit:hover {
    color:green;
    text-decoration: none;
  }
  .titles h4 {
    text-indent: 2em;
    font-size: 15px;
    color:#fff;

    /*以下五行设置显示３行文本，多余隐藏*/
    overflow : hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
  }
  .titles span {
    color:#9400d3;
  }
  .sear {
    color:red;
    font-size: 12px;
  }
  .sear:hover{
    color:red;
    text-decoration: none;
  }
  .pinglun {
    color:orange;
    font-size: 12px;
    margin-left: 10px;
  }
  .pinglun:hover {
    color:red;
    text-decoration: none;
  }
  .right {
    width:300px;
    height:200px;
    border:1px solid #FFF;
    position: absolute;
    right:-350px;
    top:0px;
    background: rgba(255, 228, 225, 0.2);
    border-radius: 5px;
  }
  .right div {
    font-size: 20px;
    text-align: center;
    color:#00ff00;
  }
  .tubiao a {
    /*transform-style: preserve-3d;*/
    width:36px;
    height:36px;
    margin-left: 19px;
    float:left;
    display: inline-block;
    transform:scale(1);
    transition:transform 0.2s ease-in;
  }
  .tubiao a:nth-child(1){
    background: url("{%static 'images/tubiao.png'%}") 0px -78px;
  }
  .tubiao a:nth-child(2){
    background: url("{%static 'images/tubiao.png'%}") 0px -118px;
  }
  .tubiao a:nth-child(3){
    background: url("{%static 'images/tubiao.png'%}") 0px -157px;
  }
  .tubiao a:nth-child(4){
    background: url("{%static 'images/tubiao.png'%}") 0px -197px;
  }
  .tubiao a:nth-child(5){
    background: url("{%static 'images/tubiao.png'%}") 0px -236px;
  }
  .tubiao a:hover {
    transform:scale(2);
  }
  .write {
    height:500px;
    font-size: 15px;
  }
  .artic_can {
    position: absolute;
    left:50%;
    top:50%;
    margin-left: -585px;
    margin-top: -230px;
  }
  .write_form span {
    color:red;
    font-size: 20px;
  }
  .ke-container{
    background-color: rgba(255, 255, 255, 0.5);
    border-radius: 5px;
  }
  .go_write {
    margin:23px;
  }
  .write_form .form-control {
    background: rgba(248,248,255,0.5);
  }
  .looks,.selfs {
    position:absolute;
    left:50%;
    top:50%;
    margin-left: -585px;
    margin-top: -200px;
    border:1px solid #fff;
    border-radius: 5px;
    background: rgba(248,248,255,0.5);
  }
  .looks h3 {
    color:blue;
  }
  .looks h4 {
    color:#000;
    text-indent: 2em;
  }
  .looks span {
    color:#9400d3
  }
  .selfs div {
    color:red;
    font-size: 25px;
  }
  .yes .fenye li a {
    background: rgba(72, 118, 255, 0.5);
    color:#fff;
  }
  #video {
    width:800px;
    height:500px;
    position:absolute;
    left:50%;
    top:50%;
    margin-left: -250px;
    margin-top: -200px;
    border:1px solid #fff;
    background: #fff;
  }
  .huanye:hover {
    background: #fff;
  }
  </style>
</head>
<body>
  <canvas id="canvas"></canvas>
    {%include 'head.html'%}

    {% if page == 11 %}

      {%include 'lunbo.html'%}

    {%elif page <= 3 %}

    <div class="container center">
      <ul class="article">
        {%for i in articles%}
        <li class="titles">
          <a href="/look/?ids={{i.id}}" class="tit">{{i.title}}</a>
          <h4>{{i.content}}......</h4><a href="/look/?ids={{i.id}}" class="sear">[查看全部]</a><br>
          <span>{{i.time}}</span>
          <a href="" class="pinglun">评论(500)</a>
          <a href="" class="pinglun">赞(55)</a>
        </li>
        {%endfor%}

        <nav aria-label="Page navigation" class="yes">
          <ul class="pagination fenye">
            {% if articles.has_previous %}
            <li><a href="?pags={{ articles.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;上一页</span>
            </a></li>
            {% else %}
            <li class="disabled"><a href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;上一页</span>
            </a></li>
            {% endif %}
            <!-- <li>{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li> -->
            {% for i in pages%}
            <li><a href="?pags={{i}}">{{i}}</a></li>
            {%endfor%}
            {% if articles.has_next %}
            <li> <a href="?pags={{ articles.next_page_number }}" aria-label="Next" class="huanye">
              <span aria-hidden="true">下一页&raquo;</span>
            </a></li>
            {% else %}
            <li class="disabled"><a href="#" aria-label="Next">
              <span aria-hidden="true">下一页&raquo;</span>
            </a></li>
            {% endif %}
          </ul>
        </nav>

        <div class="right">
          <div>分享</div>
          <div class="tubiao">
            <a href="https://qzone.qq.com/"></a>
            <a href="http://weibo.com"></a>
            <a href="http://www.baidu.com"></a>
            <a href="http://www.renren.com"></a>
            <a href="http://t.qq.com/"></a>
          </div>
          <a href="/write/" class="btn btn-danger go_write">说点什么吧</a>
        </div>
      </ul>
    </div>

    {%elif page == 10%}
    <div class="selfs">
    {%for i in users%}
      <div class="username">{{i.username}}</div>
      <div class="email">{{i.email}}</div>
    {%endfor%}
      <a href="/logout/" class="btn btn-success">退出登录</a>
    </div>
    <video id="video" controls poster="{%static 'images/angela.jpg'%}">
      <source src="{%static 'mp.mp4'%}">
    </video>
    {%elif page == 12%}
      {%include 'article.html'%}
    {%elif page == 13%}
    <div class="container looks">
      <h3>{{databases.title}}</h3>
      <h4>{{databases.content}}</h4>
      <span>{{databases.time}}</span>
    </div>
    {%endif%}

</body>
<script src="{%static 'js/lunbo.js'%}" charset="utf-8"></script>
<script src="{%static 'js/main_canvas.js'%}" charset="utf-8"></script>
<script type="text/javascript">
  $(".xiala").hover(function(){
    $(".xiala1").stop()
    $(".xiala1").fadeIn(800)
    $(".xiala1").css("z-index","100")
    $(".box").css("margin-top","0px")
  },function(){
    $(".xiala1").stop()
    $(".xiala1").fadeOut(800)
    $(".box").css("margin-top","-200px")
  })
</script>
</html>