django/myblog/myblog/urls.py
#coding=utf-8
"""myblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.views.generic.base import RedirectView
from myapp import views

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     url(r'^hello/$', views.hello),
# ]

#多重路由的引用,
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include("myapp.urls")),
    url(r'^', include('usr.urls')),
    url(r'^favicon\.ico/$',RedirectView.as_view(url='/static/favicon.ico'),name = 'favicon'),
    url(r"^media/(?P<path>.*)$",serve,{"document_root":settings.MEDIA_ROOT}),
]

django/myblog/usr/urls.py
#coding=utf-8

from django.conf.urls import url
from usr.views import *

urlpatterns = [
    url(r'^$', index),
    url(r'^search_form/$', search_form),
    url(r'^form_post/$', form_post),
    url(r'^form_post/thanks/$', thanks),
    url(r'^request/$', get_request),
    url(r'^formtest/$', formtest),
    url(r'^authorform/$', authorset),
]

###cookie  session
# urlpatterns += [
#     url(r'^login/$', login),
#     url(r'^index1/$', index),
#     url(r'^logout/$', logout),
# ]

###register login logout

urlpatterns += [
    url(r'^reg/$',reg, name="reg"),
    url(r'^login/$',login, name="login"),
    url(r'^logout/$',logout, name="logout"),
    url(r'^login_test/$', login_test,name = "login_test"),
    url(r'^thanks/$', thanks),
    url(r'^avatar/$', avatar),
]

urlpatterns += [
    url(r'^page/$', page),
    url(r'^avatar/$', avatar),
    url(r'^article/$', article),
    url(r'^upload/(?P<dir_name>[^/]+)$',upload),
]

urlpatterns += [
    url(r'^cache/$', cache),
]

django/myblog/myapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# class BetterCharField(models.Field):
#     def __init__(self,length,*args,**kwargs):
#         self.length = length
#         super(BetterCharField,self).__init__(*arg)
#     def db_type(self,connection):
#         return 'char(%s)'%self.length
# class MyModel(models.Model):
#     my_field = BetterCharField(25)



class BookQuerySet(models.QuerySet):
    def little(self):
        return self.filter(id__lt = 4)
class BookManager(models.Manager):
    # def get_queryset(self):
    #     return BookQuerySet(self.model,using = self)

    def title_count(self,keyword):
        return self.filter(title__icontains = keyword).count()

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length = 30,verbose_name = "姓名")
    address = models.CharField(max_length = 50)
    city = models.CharField(max_length = 60)
    state_province = models.CharField(max_length = 30)
    country = models.CharField(max_length = 50)
    website = models.URLField(verbose_name = "网址")

    #设置查询内容对外显示的文字
    def __unicode__(self):
        return self.name
    # ordering是排序方式，按什么排序
    class Meta:
        #数据表显示的名字
        verbose_name = "出版社"
        verbose_name_plural = verbose_name
        ordering = ['name']

class Author(models.Model):
    first_name = models.CharField(max_length = 30)
    last_name = models.CharField(max_length = 30)

    email = models.EmailField(blank = True,verbose_name = 'e-mail')
    def __unicode__(self):
        return u"%s %s"%(self.first_name,self.last_name)
    class Meta:
        verbose_name = "作者"
        verbose_name_plural = verbose_name
        ordering = ['first_name']

class Book(models.Model):
    title = models.CharField(max_length = 100)
    price = models.FloatField(default = 0.0)
    publication_date = models.DateField(blank = True,null = True)
    publisher = models.ForeignKey(Publisher)
    author = models.ManyToManyField(Author)
    objects = BookManager()
    def __unicode__(self):
        return self.title
    class Meta:
        verbose_name = "书籍"
        verbose_name_plural = verbose_name
        ordering = ['id']

django/myblog/usr/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    avatar = models.ImageField(upload_to="avatar/%Y/%m",default = "static/default.png",max_length = 200,blank = True,null = True,verbose_name = "Head_portrait")
    mobile = models.CharField(max_length = 11,blank = True,null = True,verbose_name = "tel")
    class Meta:
        verbose_name = "User"
        ordering = ['-id']
    def __unicode__(self):
        return self.username

class Image(models.Model):
    avatar = models.ImageField(upload_to="avatar/%Y/%m",default = "static/default.png",max_length = 200,blank = True,null = True,verbose_name = "Head_portrait")

django/myblog/usr/forms.py
#coding=utf-8
from django import forms
from myapp.models import Book,Author

TOPIC_CHOICES = (
    ('leve1','好评'),
    ('leve2','中评'),
    ('leve3','差评'),
)

class RemarkForm(forms.Form):
    subject = forms.CharField(max_length = 100,label = '标题')
    mail = forms.EmailField(label = '邮件')
    topic = forms.ChoiceField(choices = TOPIC_CHOICES,label = '评价')
    message = forms.CharField(label = '内容',widget = forms.Textarea)
    cc_myself = forms.BooleanField(required = False,label = '订阅')

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        #__all__就是把Author里的三列形成一个数组 ['first_name'.'last_name','email']
        fields = '__all__'
        labels = {
            'first_name':'姓',
            'last_name':'名',
            'email':'邮箱',
        }
class RegForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username","required":"required"}),max_length=50,error_messages = {"required":"Username can not be empty"})
    password=forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password","required":"required"}),max_length=20,error_messages = {"required":"password can not be empty"})
    email=forms.EmailField(widget=forms.TextInput(attrs={"placeholder":"Email","required":"required"}),max_length=50,error_messages = {"required":"Email can not be empty"})
    tel=forms.CharField(widget=forms.TextInput(attrs={"placeholder":"telephone","required":"required"}),max_length=50,error_messages = {"required":"telephone can not be empty"})
    avatar = forms.ImageField(required = False)

django/myblog/usr/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from forms import *
from myapp.models import Author,Book
from django.views.decorators.csrf import csrf_exempt
from django.contrib.sessions.models import Session
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required,permission_required
from usr.models import *
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
import os
from django.conf import settings

# Create your views here.
def index(request):

    return render(request,'form.html',{})

def search_form(request):
    print request.method
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        return HttpResponse('i hage get %s'%q)
    else:
        return render(request,'form.html',{})

def form_post(request):
    errors = []
    if request.method == 'POST':
        if not request.POST.get('subject',''):
            errors.append('Enter a subject')

        if not request.POST.get('email',''):
            errors.append('Enter a email')

        if not request.POST.get('message',''):
            errors.append('Enter message')

        if not errors:
            return redirect('/form_post/thanks')
    return render(request,"form1.html",{'errors':errors,'subject':request.POST.get('subject'),'email':request.POST.get('email'),'message':request.POST.get('message')})

def thanks(request):
    print "come on"
    print request.META.get('HTTP_REFERER')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def get_request(request):
    scheme = request.scheme
    body = request.body
    path = request.path
    method = request.method
    content = request.content_type
    get = request.GET
    post = request.POST
    cookies = request.COOKIES
    meta = request.META
    addr = request.META['REMOTE_ADDR']

    print request.get_host()
    return render(request,'request.html',locals())

def formtest(request):
    if request.method == 'POST':
        form = RemarkForm(request.POST)
        if form.is_valid():
            cd  = form.cleaned_data
            print cd['subject']
            print cd['mail']
            print cd['topic']
            print cd['message']
            print cd['cc_myself']
            return HttpResponseRedirect('/formtest')
    else:
        form = RemarkForm()

    return render(request,'formtest.html',{'form':form})

def authorset(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            cd  = form.cleaned_data
            dic = {'first_name':cd['first_name'],'last_name':cd['last_name'],'email':cd['email']}
            Author.objects.create(**dic)
            return HttpResponseRedirect('/authorform/')
    else:
        form = AuthorForm()

    return render(request,'author.html',{'form':form})

#下面这句和{%csrf_token%}功能相同

# user_info = {
#     'pangzi':{'pwd':"pang123"},
#     'shouzi':{'pwd':'shou123'}
# }
#
# @csrf_exempt
# def login(request):
#     if request.method == "GET":
#         return render(request,"login.html")
#     if request.method == "POST":
#         u = request.POST.get("username")
#         p = request.POST.get("passwd")
#         dic = user_info.get(u)
#         if not dic:
#             return render(request,'login.html')
#         if dic['pwd'] == p:
#             request.session['username'] = u
#             request.session['is_login'] = True
#             #设置存储时间20s
#             request.session.set_expiry(20)
#             return redirect('/index1/')
#         else:
#             return render(request,'login.html')
#
# def index(request):
#     if request.session.get('is_login',None):
#         return render(request,'index1.html',{'current_user':request.session['username']})
#     else:
#         return render(request,'login.html')
#
# def logout(request):
#
#     session = Session.objects.all()
#     print session
#     #清除session
#     request.session.clear()
#     return redirect('/login/')

#######register login logout######################
def thanks(request):
    return HttpResponse("thanks for your register but you not have permission_required")

#第一个参数是设置权限add,delete,change，无权限的话跳转到第二个参数的url
@permission_required('add_User',login_url = '/thanks/')
def reg(request):
    try:
        if request.method == 'POST':
            reg_form = RegForm(request.POST)
            if reg_form.is_valid():
                cd = reg_form.cleaned_data
                User.objects.create(username=cd['username'],password=make_password(cd['password']),email=cd['email'],mobile=cd['tel'],avatar = cd['avatar'])

                return HttpResponseRedirect("/login/")
            else:
                return render(request,'failure.html',{'reason':reg_form.errors})
        else:
            reg_form = RegForm()
    except Exception as e:
        print e
    return render(request,'reg.html',locals())

#当是登录状态时，输入login_test会打印这句话，若没有登录会跳转到这个路径
@login_required(login_url = '/login/')
def login_test(request):
    return HttpResponse('thank you for login')

def login(request):
    errors = []
    if request.method == "POST":
        username = request.POST.get('username',"")
        password = request.POST.get('password',"")
        if not username:
            errors.append('enter a username')
        if not password:
            errors.append('enter a password')
        if not errors:
            #验证user是否合法
            if not request.user.is_authenticated():
                user = auth.authenticate(username = username,password = password)
                if user is not None and user.is_active:
                    #让user登录
                    auth.login(request,user)
                    # return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))
                    return HttpResponseRedirect(request.GET.get('next','/'))
                else:
                    return HttpResponse("username or password invalid")
            else:
                return HttpResponse("you have already login")
    return render(request,"user_login.html",{'errors':errors})

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/login/')

def avatar(request):
    images = request.POST.get('avatar','')
    print images
    return render(request,'avatar.html',{})

def page(request):
    article_list = ['a1','a2','a3','a4','a5','a6','a7','a8']
    paginator = Paginator(article_list,5)

    #获取当前页为几页
    p = int(request.GET.get('page',1))

    article_list = paginator.page(p)

    pages = range(1,article_list.paginator.num_pages + 1)
    return render(request,'page.html',locals())

def avatar(request):
    if request.method == "POST":
        myFile = request.FILES.get('avatar',None)
        if not myFile:
            return HttpResponse('no file')
        dest = open(os.path.join(settings.MEDIA_ROOT,myFile.name),'wb+')
        Image.objects.create(avatar = os.path.join(settings.MEDIA_URL,myFile.name))

        for i in myFile:
            dest.write(i)
        dest.close()
        return HttpResponse("upload over")
    return render(request,'avatar.html',{})

def article(request):
    errors = []
    if request.method == 'POST':
        if not request.POST.get('title',''):
            errors.append('Enter a title')

        if not request.POST.get('desc',''):
            errors.append('Enter a desc')

        if not request.POST.get('content',''):
            errors.append('Enter content')

        if not errors:
            return HttpResponse("Thank you.....")
        else:
            return render(request,"article.html",{'errors':errors,'title':request.POST.get('title'),'desc':request.POST.get('desc'),'content':request.POST.get('content')})

    return render(request,"article.html")
# @csrf_exempt
# def upload(request,dir_name):
#      ##################
#     # 这是kindeditor想要的格式
#     #  kindeditor图片上传返回数据格式说明：
#     # {"error": 1, "message": "出错信息"}
#     # {"error": 0, "url": "图片地址"}
#     ##################
#     result = {"error": 1, "message": "上传出错"}
#     #imgFile来自于附文本编辑器查看源码之后找到的它定义的文件名字
#     files = request.FILES.get("imgFile", None)
#     if files:
#         return HttpResponse('okle')
#     return HttpResponse('error')


import uuid
import json
import datetime as dt
#这个装饰器用于不再进行表单验证提交
@csrf_exempt
def upload(request, dir_name):
    ##################
    # 这是kindeditor想要的格式
    #  kindeditor图片上传返回数据格式说明：
    # {"error": 1, "message": "出错信息"}
    # {"error": 0, "url": "图片地址"}
    ##################
    result = {"error": 1, "message": "上传出错"}
    #imgFile来自于附文本编辑器查看源码之后找到的它定义的文件名字
    files = request.FILES.get("imgFile", None)
    if files:
        result =image_upload(files, dir_name)
    return HttpResponse(json.dumps(result), content_type="application/json")

#目录创建
def upload_generation_dir(dir_name):
    today = dt.datetime.today()
    dir_name = dir_name + '/%d/%d/' %(today.year,today.month)
    if not os.path.exists(settings.MEDIA_ROOT + dir_name):
        os.makedirs(settings.MEDIA_ROOT + dir_name)
    return dir_name

# 图片上传
def image_upload(files, dir_name):
    #允许上传文件类型
    allow_suffix =['jpg', 'png', 'jpeg', 'gif', 'bmp']
    file_suffix = files.name.split(".")[-1]
    if file_suffix not in allow_suffix:
        return {"error": 1, "message": "图片格式不正确"}

    relative_path_file = upload_generation_dir(dir_name)

    path=os.path.join(settings.MEDIA_ROOT, relative_path_file)

    if not os.path.exists(path): #如果目录不存在创建目录
        os.makedirs(path)

    file_name=str(uuid.uuid1())+"."+file_suffix
    path_file=os.path.join(path, file_name)
    file_url = settings.MEDIA_URL + relative_path_file + file_name
    #写入操作，二进制形式，最终完成上传，真正保存图片
    open(path_file, 'wb').write(files.file.read())
    return {"error": 0, "url": file_url}

#设置缓冲时间,第二种，针对页面设置缓冲
# from django.views.decorators.cache import cache_page
#

django/myblog/usr/templates/article.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>写点什么</title>
    <script type="text/javascript" src="/static/js/kindeditor-4.1.10/kindeditor-min.js"></script>
    <script type="text/javascript" src="/static/js/kindeditor-4.1.10/lang/zh_CN.js"></script>
    <script type="text/javascript" src="/static/js/kindeditor-4.1.10/config.js"></script>
  </head>
  <body>
    <div id="content" class="colM">
    <h1>我的文章</h1>
    {%if errors%}
    <ul>
      {%for error in errors%}
        <li>{{error}}</li>
      {%endfor%}
    </ul>
    {%endif%}
    <form enctype="multipart/form-data" action="" method="post" id="article_form">
      {%csrf_token%}
      <fieldset class="module aligned ">
        <div class="form-row field-title">
            <div>
              <label class="required" for="id_title">文章标题:</label>
              <input type="text" name="title" id="id_title"  maxlength="50" value = "{{title}}"/>
            </div>

        </div>
          <hr>
            <div class="form-row field-desc">
              <div>
                <label class="required" for="id_desc">文章描述:</label>
                <input type="text" name="desc" id="id_desc" maxlength="50"  value = "{{desc}}"/>
              </div>

            </div>
          <hr>
        <div class="form-row field-content">
              <div>
                  <label class="required" for="id_content">文章内容:</label>
                  <textarea name="content" id="id_content"  value = "{{content}}"></textarea>

              </div>

        </div>
        <input type="submit" value="保存" class="default" name="_save" />
      </form>
  </body>
</html>

django/myblog/usr/templates/author.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>Form test 1</h1>
    {{a}}
    <form class="" action="" method="post">
    {%csrf_token%}
    {%for field in form%}
    <div>
      {{field.label}}:{{field}}
      {{field.errors}}
    </div>
    {%endfor%}
    <div class = "fieldWrapper">
      <p><input type="submit" value = "添加"></p>
    </div>
    </form>

</body>
</html>

django/myblog/usr/templates/avatar.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>图像上传</title>
  </head>
  <body>
    <form class="" action="" method="post" enctype="multipart/form-data">
      {%csrf_token%}
			<input type="file" name="avatar" required id="id_avatar" />
      <input type="submit" value="上传">
    </form>
  </body>
</html>

django/myblog/usr/templates/cache.html
{%load cache%}
<!DOCTYPE html>
<!-- 这是第三种设置缓冲的方法，全局的三个中间件必须得注释掉 -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>cache</title>
</head>

<body>
  <h1>{{ctime}}</h1>
  <h1>{{ctime}}</h1>
  {%cache 5 ha%}
  <h1>{{ctime}}</h1>
  <h1>{{ctime}}</h1>
  {%endcache%}
</body>
</html>

django/myblog/usr/templates/failure.html
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">

	<title>Failure</title>
	
</head>
<body>
	<div id="name">
		<span>{{reason | safe}}</span>	
	</div>
</body>
</html>

django/myblog/usr/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>form 表单</title>
</head>
<body>
  <form action="/search_form/" method="get">
    <input type="text" name="q">
    <input type="submit" value="提交">
  </form>
</body>
</html>

django/myblog/usr/templates/form1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>form 表单</title>
</head>
<body>
  <h1>Contact us</h1>
  {%if errors%}
  <ul>
    {%for error in errors%}
    <li>{{error}}</li>
    {%endfor%}
  </ul>
  {%endif%}

  <form class="" action="/form_post/" method="post">
    {%csrf_token%}
    <p>主题：<input type="text" name = "subject" value = "{{subject}}"></p>
    <p>邮箱：<input type="text" name = "email" value = "{{email}}"></p>
    <p>内容：<textarea name="message" cols="50" rows="10">{{message}}</textarea></p>
    <input type="submit" value = "提交">
  </form>

</body>
</html>

django/myblog/usr/templates/formtest.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>Form test 1</h1>
    {{a}}
    <form class="" action="" method="post">
    {%csrf_token%}
    <!-- {%for field in form%}
    <div>
      {{field.label}}:{{field}}
      {{field.errors}}
    </div>
    {%endfor%} -->
    {{form.as_p}}
    <div class = "fieldWrapper">
      <p><input type="submit" value = "留言"></p>
    </div>
    </form>

</body>
</html>

django/myblog/usr/templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <h1>{{current_user}}</h1>
  <a href="/logout/">注销</a>
</body>
</html>

django/myblog/usr/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>login</title>
</head>
<body>
  <form action="/login/" method="post">
    <input type="text" name="username" value="">
    <input type="password" name="passwd">
    <input type="submit" name="" value="登录">
  </form>
</body>
</html>

django/myblog/usr/templates/page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.css" rel="stylesheet">
  <title>分页器</title>
</head>
<body>
  {%for article in article_list%}
    {{article}}
    {%endfor%}
    <nav aria-label="Page navigation">
    	<ul class="pagination">
    		{% if article_list.has_previous %}
        <li><a href="?page={{ article_list.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a></li>
    		{% else %}
        <li class="disabled"><a href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a></li>
    		{% endif %}
    		<!-- <li>{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li> -->
        {% for i in pages%}
         <li><a href="?page={{i}}">{{i}}</a></li>
        {%endfor%}
        {% if article_list.has_next %}
        <li> <a href="?page={{ article_list.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a></li>
        {% else %}
        <li class="disabled"><a href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a></li>
    		{% endif %}
    	</ul>
    </nav>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.js"></script>
</body>
</html>

django/myblog/usr/templates/reg.html
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">

	<title>Reg</title>

</head>
<body>
	<div id="main">
		<div id="header">
			<h1>Create a free Account</h1>
		</div>
		<p>
		<form action="{%url 'reg'%}" method="post" accept-charset="utf-8">
		{%csrf_token%}
		<ul>
		<h2>New User</h2>
		<li>
			{{reg_form.username}}
		</li>
		<li>
			{{reg_form.password}}
		</li>
		<li>
			{{reg_form.email}}
		</li>
		<li>
			{{reg_form.tel}}
		</li>
		<li>
			{{reg_form.avatar}}
		</li>

			<input type="submit" value="Create And Login">
		</ul>
			</form>
		</p>
	</div>
</body>
</html>

django/myblog/usr/templates/request.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <p>scheme:{{scheme}}</p>
  <p>body:{{body}}</p>
  <p>path:{{path}}</p>
  <p>method:{{method}}</p>
  <p>content_type:{{content}}</p>
  <p>get:{{get}}</p>
  <p>post:{{post}}</p>
  <p>cookies:{{cookies}}</p>
  <P>meta:{{meta}}</P>
  <P>meta.addr:{{addr}}</P>
  <p>meat.url:{{url}}</p>
</body>
</html>

django/myblog/usr/templates/user_login.html
<html>
<head>
    <title>login</title>
</head>
<body>
    <h1>login</h1>
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <p> username<input type="text" name= "username" value="{{ username }}"></p>
        <p>password<input type="password" name="password" value="{{ password }}">
        <input type="submit" value="Submit">
     </form>
</body>
</html>